name: CI-CD Spring Boot with ArgoCD

on:
  push:
    branches: ["main"]

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./app
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/springboot-app:${{ github.sha }}

      - name: Update image tag in manifests
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          cd manifests
          sed -i "s#image: .*#image: ${{ secrets.DOCKERHUB_USERNAME }}/springboot-app:${{ github.sha }}#" deployment.yaml
          git add deployment.yaml
          git commit -m "Update image tag to ${{ github.sha }}"
          git push
